cashflow/cashflow/urls.py
from django.contrib import admin
from django.urls import path

from flow import views

app_name = 'cashflow'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    # path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # path('profile/<str:username>/', views.profile, name='profile'),
    # path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    # path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    # path(
    #     'posts/<int:post_id>/comment/',
    #     views.add_comment,
    #     name='add_comment'
    # ),
    # path('follow/', views.follow_index, name='follow_index'),
    # path(
    #     'profile/<str:username>/follow/',
    #     views.profile_follow,
    #     name='profile_follow'
    # ),
    # path(
    #     'profile/<str:username>/unfollow/',
    #     views.profile_unfollow,
    #     name="profile_unfollow"
    # ),
]

cashflow/flow/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class Status(models.Model):
    """Модель для таблицы 'Статус'"""

    value = models.CharField(
        max_length=100,
        blank=False,
        unique=True,
        verbose_name='Статус'
    )

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'
        ordering = ['value',]

    def __str__(self):
        return self.value


class Type(models.Model):
    """Модель для таблицы 'Тип'"""

    value = models.CharField(
        max_length=100,
        blank=False,
        unique=True,
        verbose_name='Тип'
    )

    class Meta:
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'
        ordering = ['value',]
    
    def __str__(self):
        return self.value


class Category(models.Model):
    """Модель для таблицы 'Категория'"""

    value = models.CharField(
        max_length=100,
        blank=False,
        unique=True,
        verbose_name='Категория'
    )
    type = models.ForeignKey(
        Type, on_delete=models.CASCADE, related_name="categories_type", verbose_name="Тип"
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.value

class Subcategory(models.Model):
    """Модель для таблицы Подкатегории"""

    value = models.CharField(
        max_length=100,
        blank=False,
        unique=True,
        verbose_name="Подкатегория"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        blank=False,
        related_name='category_subcategory',
        verbose_name='Связная категория'
    )

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Пождкатегории'
        ordering = ['value', 'category']

    def __str__(self):
        return self.value


class Post(models.Model):
    pub_date_verbose_name_title = 'Дата создания записи'
    user_verbose_name_title = "Пользователь"
    status_verbose_name_title = 'Статус'
    flow_type_verbose_name_title = 'Тип'
    category_verbose_name_title = 'Категория'
    subcategory_verbose_name_title = 'Подкатегория'
    amount_verbose_name_title = 'Сумма'
    comment_verbose_name_title = 'Комментарий'

    pub_date = models.DateField(
        auto_now_add=True,
        editable=True,
        verbose_name=pub_date_verbose_name_title
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=False,
        related_name='user_post',
        verbose_name=user_verbose_name_title
    )
    status = models.ForeignKey(
        Status,
        related_name='post_status',
        on_delete=models.CASCADE,
        verbose_name=status_verbose_name_title
    )
    type = models.ForeignKey(
        Type,
        related_name='post_flow_type',
        on_delete=models.CASCADE,
        blank=False,
        verbose_name=flow_type_verbose_name_title
    )
    category = models.ForeignKey(
        Category,
        related_name='post_category',
        on_delete=models.CASCADE,
        blank=False,
        verbose_name=category_verbose_name_title
    )
    subcategory = models.ForeignKey(
        Subcategory,
        related_name='post_subcategory',
        on_delete=models.CASCADE,
        blank=False,
        verbose_name=subcategory_verbose_name_title
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=False,
        verbose_name=amount_verbose_name_title
    )
    comment = models.TextField(
        max_length=906,
        blank=True,
        verbose_name=comment_verbose_name_title + ' (необязательно)'
    )

    class Meta:
        verbose_name = 'Запись о ДДС'
        verbose_name_plural = 'Записи о ДДС'
        ordering = ['pub_date']

    def __str__(self) -> str:
        return self.status.value
    
    def clean(self):
        # Проверка соответсвия категории и подкатегории
        if self.subcategory and self.subcategory.category != self.category:
            raise ValidationError(
                "Подкатегория не соответствует выбранной категории"
            )
        # Проверка соответсвия категории и типа
        if self.category and self.category.type != self.type:
            raise ValidationError("Категория не соответствует выбранному типу")

cashflow/flow/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            # 'pub_date',
            'user',
            'status',
            'type',
            'category',
            'subcategory',
            'amount',
            'comment'
        )

cashflow/flow/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.shortcuts import get_object_or_404

from . models import Post, Status, Type, Category, Subcategory
from . forms import PostForm
from . utils import page_obj_gen

def index(request):
    posts = Post.objects.all()
    page_obj = page_obj_gen(request, posts)
    title = 'Движение денежных средств'
    context = {
        'page_obj': page_obj,
        'title': title,
        'pub_date_field_title': Post.pub_date_verbose_name_title,
        'user_field_title': Post.user_verbose_name_title,
        'status_field_title' : Post.status_verbose_name_title,
        'type_field_title': Post.flow_type_verbose_name_title,
        'category_field_title': Post.category_verbose_name_title,
        'subcategory_field_title': Post.subcategory_verbose_name_title,
        'amount_field_title': Post.amount_verbose_name_title,
        'comment_field_title': Post.comment_verbose_name_title
        # 'index': True,
    }
    return render(request, 'index.html', context)

@login_required
def post_create(request):
    form = PostForm (
        request.POST or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        return redirect('cashflow:index')
    title = 'Новая запись'
    context = {
        'form': form,
        'is_edit': False,
        'title': title
    }
    return render(request, 'post_create.html')

cashflow/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">        
      <title>{% block title %}Название страницы - его тайтл{% endblock %}</title>       
  </head>
  <body>
      {% include 'includes/header.html' %}
    <main>
      {% block content %}  
        должны были подвезти контент     
      {% endblock %}
    </main>
      {% include 'includes/footer.html' %}
  </body>
</html> 

cashflow/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>Test Task <span style="color:red">CASH</span>FLOW</p>
</footer>    

cashflow/templates/includes/header.html
<header>
  <!-- заголовок страницы -->
</header>

cashflow/templates/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
{% load verbose_names %}
{% load thumbnail %}
{% load cache %}
{% cache 20 index_page %}

<table>
  <tr style="background-color:darkgray">
    <td>{{ pub_date_field_title }}</td>
    <td>{{ user_field_title }}</td>
    <td>{{ status_field_title }}</td>
    <td>{{ type_field_title }}</td>
    <td>{{ category_field_title }}</td>
    <td>{{ subcategory_field_title }}</td>
    <td>{{ amount_field_title }}</td>
    <td>{{ comment_field_title }}</td>
  </tr>

  {% for post in page_obj %} 
  <tr>
    <td>{{ post.pub_date|date:"d.m.Y" }}</td>
    <td>{{ post.user }}</td>
    <td>{{ post.status }}</td>
    <td>{{ post.type }}</td>
    <td>{{ post.category }}</td>
    <td>{{ post.subcategory }}</td>
    <td>{{ post.amount }}</td>
    <td>{{ post.comment }}</td>
  </tr>
  {% endfor %}

</table>
{% endcache %} 
  

{% endblock %} 

cashflow/templates/post_create.html
{% extends 'base.html' %}
 {% block title %}{{ title }}{% endblock %} 
  {% block content %}
  <body>	       
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                  Редактирование поста        
                {% else %}
                  Новый пост
                {% endif %}           
              </div>
              <div class="card-body"> 
              
               {% load user_filters %}      
                <form method="post" enctype="multipart/form-data" action="{% url 'cashflow:post_create' %}">
                   {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              {% csrf_token %} 
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                   {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4" align='right'>
                <button type="submit" class="btn btn-primary">Добавить </button>
               
              </div>
            </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    </body>
</html>
{% endblock %}